basePath: /
definitions:
  server.Error:
    properties:
      error: {}
    type: object
  server.Response:
    properties:
      data: {}
    type: object
host: localhost:8080
info:
  contact: {}
  description: api server for social network
  title: Social Network API
  version: "0.1"
paths:
  /api/v1/follow/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Target user ID to follow
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/server.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/server.Error'
      summary: Follow a user
      tags:
      - users
  /users/create:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "201":
          description: ok
          schema:
            type: string
      summary: Sign up
      tags:
      - users
swagger: "2.0"
