name: Svelte Docker Image CD Deployment

on:
  workflow_run:
    workflows: ["Svelte Docker Image CD"]
    types: 
      - completed

jobs:
  build:

    runs-on: svelte-runner

    steps:

    - name: Pulling docker image from dockerhub.
      run: sudo docker pull mannuk24/sn-svelte-fe:latest
    - name: Deleting old docker container
      run: sudo docker rm -f sn-svelte-fe-container || true
    - name: Running docker container
      run: sudo docker run -d -p 5000:5000 --name sn-svelte-fe-container mannuk24/sn-svelte-fe
