name: Terraform Apply

on:
  push:
    branches: ["dev"]

jobs:
  terraform:
    name: 'Terraform'
    env:
      #AWS Secret access key and access key from github secrets
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.3
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: 'infra'
        tf_actions_comment: true
      # run: terraform init
      # working-directory: infra
      # env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Terraform Plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: 'infra'
        tf_actions_comment: true

    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_subcommand: 'apply'
        tf_actions_working_dir: 'infra'
        tf_actions_comment: true
        





    # - name: Terraform Apply
    #   run: terraform apply -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    #   working-directory: infra
    #   env:
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       AWS_REGION: ${{ secrets.AWS_REGION }}